### ISSUE TITLE
Does is work with Mumbai?

### ISSUE THREAD

**Issue by usmansharif525** [poma/hardhat-etherscan-abi#6]
I am trying to make it work with Mumbai test net, but so far unsuccessful...

> NomicLabsHardhatPluginError: An etherscan endpoint could not be found for this network. ChainID: 80001. The selected network is mumbai.

> Possible causes are:
>   - The selected network (mumbai) is wrong.
>   - Faulty hardhat network config.
> 
>  If you use Mainnet fork mode try setting 'chainId: 1' in hardhat config
>     at Object.getEtherscanEndpoints (/home/usman/Desktop/Projects/Navigate/node_modules/hardhat-etherscan-abi/src/network/prober.ts:87:11)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at getVerifiedContractAt (/home/usman/Desktop/Projects/Navigate/node_modules/hardhat-etherscan-abi/src/helpers.ts:28:20)

**Comment by Metroxe** [comment]
Added in the Mumbai testnet in #7
